### ISSUE TITLE
Is there a limit count of entitlements when using patchEntitlements?

### ISSUE THREAD

**Issue by xuanxt** [jakeajames/jelbrekLib#1]
Hi @jakeajames 
The repo is awesome! But I have problem when I use it.

The entitlements of patchEntitlements() seem has limit.
It return true when entitlements count are six,but it return false when entitlements count more than six.

Is there something wrong that I did?

**Comment by xuanxt** [comment]
The "replace" meant that I should only set the equal entitlements count of my origin entitlements count?

**Comment by xuanxt** [comment]
I debug the code.It seems entitlementString's length > blob->data's length cause some failure.
`if (strlen(entitlementString) + strlen("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\n</dict>\n</plist>\n") > strlen(blob->data))`

**Comment by jakeajames** [comment]
Hi there, you cannot make the entitlements bigger than they are. A feature to allocate new entitlements is there but it's highly experimental and buggy. I have to revisit that code.

Thank you

**Comment by jakeajames** [comment]
Hello, latest commit disables the feature but also includes a fix. It's disabled for the sole reason that the device panics after a while after exiting app. I'm not entirely sure but could be caused from replacing pointers in the blob. If you want you try can uncommenting the code and restoring the original blob back after being done with it.
