### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by brandonplank** [jakeajames/jelbrekLib#11]
Stuck at 

[i] offsets selected for iOS 13.0 or above
[*] copying to /var/mobile/Containers/Data/Application/017BDE09-9DE3-4F75-A027-7A1F85A05AE1/Documents/22.03.20:18.30.25_kernelcache

used
init_with_kbase(tfp0, kbase, NULL);
                uint64_t trustcache = Find_trustcache();

**Comment by jakeajames** [comment]
Find where it gets stuck exactly. Follow all functiom calls

**Comment by brandonplank** [comment]
alright

**Comment by jakeajames** [comment]
Please try now. And please test with Find_allproc() instead. Also logging via printf() might be broken (at least it was for the one who was testing it, not sure why),  use lldb or something like an alert instead.

**Comment by jakeajames** [comment]
patchfinder fix is confirmed working and printf issue was also just fixed
