### ISSUE TITLE
Failed to initialize patchfinder

### ISSUE THREAD

**Issue by cakarlen** [jakeajames/jelbrekLib#12]
Device: iPhone 7+, iOS 13.1.2
Jailbreak: Latest checkra1n

I built a small tool to learn more about kernel internals and wanted to use jelbrekLib to accomplish some tasks.
I am unable to initialize jelbrekLib though because of failing to initialize patchfinder. Is this an issue stemming from checkra1n or this library?

Here is the log of the tool when starting:
```
tfp0: 0x2507
Kernel slide: 0x1f104000
[*] Initializing jelbrekLib
[i] offsets selected for iOS 13.0 or above
[*] copying to /var/root/Documents/02.04.20:17.20.38_kernelcache
[+] Initialized KernelSymbolFinder
[-] Failed to initialize patchfinder
Initialization failed! ret: 3
```

Here is the main function of my tool (very simple code):
```
int main(int argc, char **argv) {
    printf("Start\n");
    
    get_tfp0();
    get_kaslr_slide();

    int ret = init_with_kbase(tfp0, 0xfffffff007004000 + kaslr_slide, NULL);

    if (ret != 0) {
        printf("Initialization failed! ret: %d\n", ret);
        return ret;
    }

    term_jelbrek();
    printf("Dealloc'd jelbrekLib\n");
    return 0;
}
```

**Comment by cakarlen** [comment]
Looks like the issue was this piece:
```
#define MACHO(p) ((*(unsigned int *)(p) & ~1) == 0xfeedface)

if (!MACHO(buf)) {
     printf("[patchfinder] Not MachO file!\n");
     close(fd);
     return -1;
 }
```

The reason for this is because the magic of my kernelcache is `0xfeedfacf`. Commenting out the above code will init jelbrekLib correctly, but this check obviously needs to stay.

**Comment by c834606877** [comment]
same problem

**Comment by jakeajames** [comment]
The MACHO macro will check for both 0xfeedfacf and 0xfeedface (look at the & ~1)

**Comment by c834606877** [comment]
yes, just figueout there have little bug in patchfinder.

**Comment by jakeajames** [comment]
No there is not. Did you even read my comment? Please find the real reason why it fails. Place logs or breakpoints in all "return -1"s

**Comment by cakarlen** [comment]
> No there is not. Did you even read my comment? Please find the real reason why it fails. Place logs or breakpoints in all "return -1"s

Used this advice of putting `printf` with an arbitrary message in each `return -1` in `patchfinder.m`.
It fails at the same piece of code I posted above:
```
if (!MACHO(buf)) {
     printf("[patchfinder] Not MachO file!\n");
     close(fd);
     return -1;
 }
```

Log of my tool:
```
tfp0: 0x2507
Kernel slide: 0x1d750000
[*] Initializing jelbrekLib
[i] offsets selected for iOS 13.0 or above
[*] copying to /var/root/Documents/04.04.20:12.24.23_kernelcache
[+] Initialized KernelSymbolFinder
[patchfinder] File magic: feedfacf
[patchfinder] Not MachO file!
[-] Failed to initialize patchfinder
Assertion failed: (ret == 0), function main, file main.m, line 47.
Abort trap: 6
```

**Comment by jakeajames** [comment]
That does not make any sense. Please log `*(uint32_t*)buf` instead of `magic`, as that is the one being checked.

Also does it ever reach this line? https://github.com/jakeajames/jelbrekLib/blob/master/patchfinder64.m#L530

**Comment by cakarlen** [comment]
Sorry, totally missed that `MACHO` is checking `buf`.

Here is the log now after logging `buf`:
```
tfp0: 0x1907
Kernel slide: 0x1d750000
[*] Initializing jelbrekLib
[i] offsets selected for iOS 13.0 or above
[*] copying to /var/root/Documents/04.04.20:15.03.37_kernelcache
[+] Initialized KernelSymbolFinder
[patchfinder] File magic: 0xfeedfacf
[patchfinder] buf: 0x100000c
[patchfinder] Not MachO file!
[-] Failed to initialize patchfinder
Assertion failed: (ret == 0), function main, file main.m, line 47.
Abort trap: 6
```

Also, it will get past line 530, but doesn't take the `if` branch.

**Comment by jakeajames** [comment]
> but doesn't take the if branch.

So it doesn't think the binary is a fat macho? I think i found the issue. I read the magic but I don't lseek back to offset 0 if it's not fat.

**Comment by jakeajames** [comment]
Newest commit should fix the issue. Will add compiled binary later.

**Comment by cakarlen** [comment]
Seems to have fixed it and going to close this. Thanks for the help.
