### ISSUE TITLE
Some question about hidePath

### ISSUE THREAD

**Issue by NyaMisty** [jakeajames/jelbrekLib#13]
I've read the source code and found the hidePath is setting VISSHADOW, which will affect vfs_lookup's behaviour.
But I'm wondering:
1. Does it work with SYS_stat-based detection?
1. Does it work with SYS_symlink-based detection?
1. Does it work with opendir & readdir based detection?

**Comment by jakeajames** [comment]
It's a kernel patch, it obviously doesn't matter whether you use normal functions, the syscall() function or do it from assembly, those are different ways to do the same thing. This will work for any kind of file access (but iirc it won't with directory listings).

Also, this patch is not suitable to use with a lot of files at once. The effects won't be permanent unless you keep said vnode forever open, which isn't possible with a lot of files a once

**Comment by NyaMisty** [comment]
Well I know that syscall() and assembly does the same thing.
However there're various syscall. Actually my question is that what operation is affected by this VISSHADOW. 
ofc, stat() is killed. But there are approaches using symlink + realpath, which is actually symlink + access behind. Will VISSHADOW flag still work?

**Comment by jakeajames** [comment]
Anything except file listings should work
