### ISSUE TITLE
Code Typo?

### ISSUE THREAD

**Issue by Naville** [jakeajames/jelbrekLib#2]
Hi:
In ``jelbrek.m`` there is the following code snippet:

```
  if (rv || !S_ISREG(st.st_mode) || st.st_size < 0x4000) {
            printf("[-] Binary too big\n");
            return 3;
        }
```

Which I believe should be ``st.st_size > 0x4000``

**Comment by jakeajames** [comment]
It shall actually be "too small" - fixed
